export const CANONICAL_SERIALIZATION_VERSION = "HLX-CANONICAL-SERIALIZATION-v1";

export const DOMAIN_TAG = Object.freeze({
  EMIM_COMMITMENT: "HLX-EMIM-COMMITMENT-v1",
  PREPCM_EXECUTION: "HLX-PREPCM-EXECUTION-v1",
  EVENT_OCCURRENCE: "HLX-EVENT-OCCURRENCE-v1",
  RENDERED_CONTENT: "HLX-RENDERED-CONTENT-v1",
  RENDER_DERIV: "HLX-RENDER-DERIV-v1",
  RENDER_PARAMS: "HLX-RENDER-PARAMS-v1",
  RESSRC: "HLX-RESSRC-v1",
  PREPCM_OUTPUT: "HLX-PREPCM-OUTPUT-v1",
  PREPCM_OUTPUT_CONTENT: "HLX-PREPCM-OUTPUT-CONTENT-v1",
  PREPCM_LINEAGE: "HLX-PREPCM-LINEAGE-v1",
  RETAUTH: "HLX-RETAUTH-v1",
  POLICY_INPUT: "HLX-POLICY-INPUT-v1",
  RESCERT_CLAIM: "HLX-RESCERT-CLAIM-v1",
  RESCERT_OCC: "HLX-RESCERT-OCC-v1",
  CERT_INPUTSET: "HLX-CERT-INPUTSET-v1",
  DEMAND_SLOT: "HMIR-DEMAND-SLOT-v1",
  DEMAND_BLUEPRINT: "HMIR-DEMAND-BLUEPRINT-v1",
  RETRIEVAL_QUAL: "HMIR-RETRIEVAL-QUAL-v1",
  FACTUAL_BASELINE: "HMIR-FACTUAL-BASELINE-v1",
  FACTUAL_SEAL: "HMIR-FACTUAL-SEAL-v1",
  SEMANTIC_BINDING: "HMIR-SEMANTIC-BINDING-v1",
  EVIDENCE_BINDING: "HMIR-EVIDENCE-BINDING-v1",
  XPI_EXECUTION: "XPI-EXECUTION-v1",
  XPI_ACCESS_EVENT: "XPI-ACCESS-EVENT-v1",
  XPI_DERIVATIVE: "XPI-PROTECTED-DERIVATIVE-v1",
  XPI_ACCESS_SET: "XPI-ACCESS-SET-v1",
  XPI_SUPPLIED_UNIVERSE: "XPI-SUPPLIED-UNIVERSE-v1",
  T0_DETERMINATION: "HLX-T0-DETERMINATION-v1",
});

export const REGION = Object.freeze({
  R0: "R0",
  R1: "R1",
  R2: "R2",
  R3: "R3",
});

export const EXECUTION_CLASS = Object.freeze({
  RESOLUTION: "HLX-A",
  RESEARCH: "HLX-B",
  EXTRACTION: "HLX-C",
  SEMANTIC_ADJUDICATION: "HLX-D",
  DERIVATION: "HLX-E",
});

export const LAWFUL_CLASSES_BY_REGION = Object.freeze({
  R0: Object.freeze([EXECUTION_CLASS.RESOLUTION]),
  R1: Object.freeze([EXECUTION_CLASS.RESEARCH, EXECUTION_CLASS.EXTRACTION]),
  R2: Object.freeze([]),
  R3: Object.freeze([EXECUTION_CLASS.SEMANTIC_ADJUDICATION, EXECUTION_CLASS.DERIVATION]),
});

export const EVENT_KIND = Object.freeze({
  AUTHORIZATION_DECISION: "AUTHORIZATION_DECISION",
  HISTORICAL_RETRIEVAL: "HISTORICAL_RETRIEVAL",
  CERTIFICATION: "CERTIFICATION",
});

export const RETRIEVAL_ROLE = Object.freeze({
  DISCOVERY: "DISCOVERY",
  SOURCE: "SOURCE",
});

export const REQUEST_KIND = Object.freeze({
  DISCOVERY: "DISCOVERY",
  SOURCE: "SOURCE",
});

export const OUTPUT_KIND = Object.freeze({
  RESOLUTION_CANDIDATE: "RESOLUTION_CANDIDATE",
  RETRIEVAL_REQUEST: "RETRIEVAL_REQUEST",
  EXTRACTION_CANDIDATE: "EXTRACTION_CANDIDATE",
  WORKING_NOTE: "WORKING_NOTE",
});

export const ITEM_CHANNEL = Object.freeze({
  SYSTEM_INSTRUCTION: "SYSTEM_INSTRUCTION",
  USER_CONTEXT: "USER_CONTEXT",
  RETRIEVED_CONTEXT: "RETRIEVED_CONTEXT",
  TOOL_RESULT: "TOOL_RESULT",
  SOURCE_EXCERPT: "SOURCE_EXCERPT",
  STRUCTURED_FACTUAL_OBJECT: "STRUCTURED_FACTUAL_OBJECT",
  PRIOR_LLM_OUTPUT: "PRIOR_LLM_OUTPUT",
  PROTECTED_DERIVATIVE: "PROTECTED_DERIVATIVE",
  ATTACHMENT: "ATTACHMENT",
  NON_HISTORICAL_INSTRUCTION: "NON_HISTORICAL_INSTRUCTION",
});

export const AUTHORITY_CLASS = Object.freeze({
  AUTHORITY_BEARING: "AUTHORITY_BEARING",
  AUTHORITY_INERT: "AUTHORITY_INERT",
});

export const ANCHOR_KIND = Object.freeze({
  RESOLUTION_SOURCE: "resolutionSourceRecordId",
  RETRIEVAL_QUALIFICATION: "retrievalQualificationId",
  PREPCM_OUTPUT: "prePcmOutputRecordId",
  SEALED_FACT: "sealedFactId",
  EVIDENCE_BINDING: "evidenceBindingId",
  PROTECTED_DERIVATIVE: "protectedDerivativeId",
  NON_HISTORICAL_INSTRUCTION: "NON_HISTORICAL_INSTRUCTION",
});

export const RENDERING_RELATION = Object.freeze({
  IDENTITY: "IDENTITY",
  TRANSFORMED: "TRANSFORMED",
});

export const AUTHORIZATION_VARIANT = Object.freeze({
  RESOLUTION_AUTHORIZATION: "RESOLUTION_AUTHORIZATION",
  STAGE_B_AUTHORIZATION: "STAGE_B_AUTHORIZATION",
});

export const AUTHORIZATION_DECISION = Object.freeze({
  AUTHORIZED: "AUTHORIZED",
  REFUSED: "REFUSED",
});

export const CERTIFICATION_RESULT = Object.freeze({
  PASS: "PASS",
  FAIL: "FAIL",
  ESCALATED_IRREDUCIBLE_AMBIGUITY: "ESCALATED_IRREDUCIBLE_AMBIGUITY",
});

export const CERTIFYING_ACTIVITY = Object.freeze({
  LLM_CERTIFICATION: "LLM_CERTIFICATION",
  DETERMINISTIC_CERTIFICATION: "DETERMINISTIC_CERTIFICATION",
});

export const CHECK_CLASS = Object.freeze({
  DETERMINISTIC: "DETERMINISTIC",
  JUDGMENT_BASED: "JUDGMENT_BASED",
});

export const G0_LIMB_A_FIELDS = Object.freeze([
  "caseId",
  "T0Identity",
  "caseSides",
  "caseGeometryVersion",
]);

export const MATH_BLOCK_ID = Object.freeze({
  MB_DOM: "MB-DOM",
  MB_ENV: "MB-ENV",
  MB_T3F: "MB-T3F",
  MB_T4: "MB-T4",
  MB_PAIR: "MB-PAIR",
  MB_RES: "MB-RES",
  MB_ECS: "MB-ECS",
  MB_FRIC: "MB-FRIC",
  MB_PRED: "MB-PRED",
  MB_TYPE: "MB-TYPE",
  MB_COHORT: "MB-COHORT",
  MB_Y: "MB-Y",
  MB_METRO: "MB-METRO",
  MB_HAKEN_A: "MB-HAKEN-A",
  MB_HAKEN_B: "MB-HAKEN-B",
});

export const DECLARED_NOT_INSTANTIATED_REASON = Object.freeze({
  OPERATOR_UNRESOLVED: "OPERATOR_UNRESOLVED",
  CONSUMER_UNRESOLVED: "CONSUMER_UNRESOLVED",
  GEOMETRY_UNESTABLISHED: "GEOMETRY_UNESTABLISHED",
  AUTHORITY_CANDIDATE: "AUTHORITY_CANDIDATE",
  APPLICABILITY_UNEVALUABLE: "APPLICABILITY_UNEVALUABLE",
  LANE_CONTRACT_UNRESOLVED: "LANE_CONTRACT_UNRESOLVED",
});

export const COLLECTION_STATUS = Object.freeze({
  COLLECTION_CLOSED: "COLLECTION_CLOSED",
  INCOMPLETE: "INCOMPLETE",
  FAIL: "FAIL",
});

export const CERTIFICATION_DISPOSITION = Object.freeze({
  CERTIFIED_AND_IN_BASELINE: "CERTIFIED_AND_IN_BASELINE",
  EXCLUDED: "EXCLUDED",
  QUARANTINED: "QUARANTINED",
});

export const RETRIEVAL_QUALIFICATION = Object.freeze({
  PROSPECTIVE: "PROSPECTIVE",
  RETROSPECTIVE: "RETROSPECTIVE",
});

export const XPI_PURPOSE = Object.freeze({
  ADJUDICATION: "ADJUDICATION",
  REPLAY_VERIFICATION: "REPLAY_VERIFICATION",
  DERIVATION: "DERIVATION",
});

export const LINEAGE_STATE = Object.freeze({
  LINEAGE_ESTABLISHED: "LINEAGE_ESTABLISHED",
  LINEAGE_NOT_ESTABLISHED: "LINEAGE_NOT_ESTABLISHED",
});

export const RULE_REF = Object.freeze({
  AUTH: Object.freeze({ identity: "HLX-AUTH-RULE", version: "v1" }),
  XR: Object.freeze({ identity: "HLX-XR-NARROW-ONLY", version: "v1" }),
  REQUEST_DERIVATION: Object.freeze({ identity: "HLX-REQUEST-DERIV", version: "v1" }),
  RENDERING_IDENTITY: Object.freeze({ identity: "HLX-RENDER-IDENTITY", version: "v1" }),
  RENDERING_TRANSFORM: Object.freeze({ identity: "HLX-RENDER-TRANSFORM", version: "v1" }),
  OUTPUT_EXTRACTION: Object.freeze({ identity: "HLX-OUTPUT-EXTRACT", version: "v1" }),
  G0_FIELD_MAP: Object.freeze({ identity: "HLX-G0-FIELD-MAP", version: "v1" }),
  CERTIFICATION: Object.freeze({ identity: "HLX-CERT-RULE", version: "v1" }),
  FACTUAL_CERTIFICATION: Object.freeze({ identity: "HMIR-FACTUAL-CERT-RULE", version: "v1" }),
});

export const R0_MANDATE_CONSTITUENTS = Object.freeze([
  "resolutionMission",
  "allowedSourceClasses",
  "allowedRetrievalMethods",
  "temporalBoundaries",
  "identityTransactionT0PurposeScope",
  "prohibitionOnEvidenceAdmission",
  "prohibitionOnOutcomeLeakage",
  "authorityInertSourceContent",
]);

export const STOPPING_RULE_AUTHORITY = "OD-HMIR-1/OD-2-A";

export const REGISTRY_VERSION = "HMIR-1.CORR5";
export const SEMANTIC_BINDING_VERSION = "v1";
export const SLOT_TYPE_VERSION = "v1";
