export const AUTHORITY_TRACEABILITY = Object.freeze([
  { clause: "HLX §6 canonicalization", carrier: "src/historical/canonical.js", tests: ["A1", "A2", "A3"] },
  { clause: "HLX §8/§13 EMIM commitment DAG", carrier: "src/historical/emim.js", tests: ["B1", "B2", "C1"] },
  { clause: "HLX §13.4 no post-start amendment", carrier: "src/historical/emim.js#assertEmimImmutable", tests: ["C1", "ADV-POST-START"] },
  { clause: "HLX §14 rendered content recoverable", carrier: "src/historical/rendering.js", tests: ["D1", "D2", "ADV-MISSING-DERIV"] },
  { clause: "HLX §16 authorization-before-retrieval", carrier: "src/historical/authorization.js", tests: ["E1", "F1", "G1"] },
  { clause: "HLX §16.2 identity containment inversion", carrier: "src/historical/retrieval.js#allocateRetrievalOccurrence", tests: ["E1", "ADV-LATE-AUTH", "ADV-ONE-AUTH-TWO-RET"] },
  { clause: "HLX §17 fan-out 0/1/N", carrier: "src/historical/retrieval.js#fanOutFromDiscovery", tests: ["H0", "H1", "HN"] },
  { clause: "HLX §17.6 fanOutDerivationLawful nine conjuncts", carrier: "src/historical/retrieval.js#fanOutDerivationLawful", tests: ["I1", "J1", "ADV-FANOUT-ABSENT"] },
  { clause: "HLX §17.6.1 XR_PERMITS narrowing only", carrier: "src/historical/rules.js#xrPermitsV1", tests: ["I1", "ADV-XR-AUTH-SPLIT"] },
  { clause: "HLX §16.4 R0 fail-closed governance", carrier: "src/historical/authorization.js#resolveR0Mandate", tests: ["K1", "ADV-R0-MISSING"] },
  { clause: "HLX §18.4 R0 evidence firewall", carrier: "src/historical/pipeline.js#offerR0SourceAsStageBEvidence", tests: ["L1", "ADV-R0-AS-EVIDENCE"] },
  { clause: "HLX §18.2 R1 retrievalOccurrenceId = retrievalActId", carrier: "src/historical/retrieval.js#executeRetrieval", tests: ["M1"] },
  { clause: "HLX §14.5 / XPI exact access reference", carrier: "src/historical/xpi.js#renderProtectedItemForEmim", tests: ["N1", "ADV-XPI-WRONG-EVENT"] },
  { clause: "HLX §15.4 lineage transitivity", carrier: "src/historical/output.js#prePcmSourceLineage", tests: ["O1"] },
  { clause: "HLX §19 certification complete-input provenance", carrier: "src/historical/certification.js", tests: ["P1", "ADV-CERT-ABSENT-SOURCE"] },
  { clause: "HLX §20 G0 field coverage", carrier: "src/historical/certification.js#g0Establishable", tests: ["Q1", "ADV-CANDIDATE-G0-SCOPE"] },
  { clause: "HLX §19.9.1 conflict semantics", carrier: "src/historical/certification.js#conflictingCertification", tests: ["R1", "R2"] },
  { clause: "HLX §21 contamination preserves event truth", carrier: "src/historical/retrieval.js#methodCreditEligible", tests: ["S1"] },
  { clause: "HMIR §11.4 / §15.1 method-exhaustion closure", carrier: "src/historical/hmir.js#evaluateCollectionClosure", tests: ["T1"] },
  { clause: "HMIR §15.6 resource cap → INCOMPLETE", carrier: "src/historical/hmir.js#markResourceCap", tests: ["U1", "ADV-RESOURCE-CAP"] },
  { clause: "HLX §7 R2 invocation prohibition", carrier: "src/historical/pipeline.js#invokeInSession", tests: ["V1", "ADV-R2"] },
  { clause: "HMIR OD-3 MB-ENV declared not instantiated", carrier: "src/historical/hmir.js#assertMbEnvUninstantiated", tests: ["W1", "ADV-ENV-INSTANTIATE"] },
  { clause: "HLX §22 no raw LLM → core", carrier: "src/historical/hmir.js#rejectRawLlmToCore", tests: ["X1", "ADV-RAW-LLM-CORE"] },
  { clause: "XPI exclusive access path", carrier: "src/historical/xpi.js", tests: ["N1", "XAD1"] },
  { clause: "HAD-1 evidence surface", carrier: "src/historical/evidenceSurfaces.js", tests: ["HAD1"] },
  { clause: "HAD-2 evidence surface", carrier: "src/historical/evidenceSurfaces.js", tests: ["HAD2"] },
]);
